fix trojan-rs compress error
trojan-rs/mobile2/backend/gen/android/app/src/main/assets : errno=2 : No such file or directory

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -400,6 +400,11 @@ jobs:
           pushd yesplaymusic/Clients || exit 1
           wget -qO- https://api.github.com/repos/qier222/YesPlayMusic/releases/latest | jq ".assets[] | {browser_download_url}" -c | jq .browser_download_url -r | aria2c -c -x 8 -s 8 -j 1 -k 1M -i -
           popd || exit 1
+          # trojan-rs
+          pushd trojan-rs || exit 1
+          echo "fix error : trojan-rs/mobile2/backend/gen/android/app/src/main/assets : errno=2 : No such file or directory"
+          rm -rf mobile2/backend/gen/android/app/src/main/assets
+          popd || exit 1
 
       - name: Compress to packages
         run: |
@@ -451,7 +456,7 @@ jobs:
           trojan-gfw
           trojan-go
           trojan-r
-          trojan-rs
+          
           trojanrust
           shadowsocks-libev
           go-shadowsocks2
